export const AppsData = [
  {
    name: "Tic-Tac-Toe",
    imageUrl: "/images/tic-tac-toe.webp",
    imageLight: "/images/tic-tac-toe-l.webp",
    iconUrl: "/images/tic-tac-toe.ico",
    linkName: "apps/tic-tac-toe",
    date: "June 9, 2023",
  },
  {
    name: "Quiz App",
    imageUrl: "/images/quiz-app.webp",
    imageLight: "/images/quiz-app-l.webp",
    iconUrl: "/images/quiz-app.ico",
    linkName: "apps/quiz-app",
    date: "June 20, 2023",
  },
  {
    name: "Translator",
    imageUrl: "/images/hindi-translator.webp",
    imageLight: "/images/hindi-translator-l.webp",
    iconUrl: "/images/hindi-translator.ico",
    linkName: "apps/hindi-translator",
    date: "June 21, 2023",
  },
  {
    name: "Chat GPT",
    imageUrl: "/images/apna-chat-gpt.webp",
    imageLight: "/images/apna-chat-gpt-l.webp",
    iconUrl: "/images/chat-gpt.ico",
    linkName: "apps/apna-chat-gpt",
    date: "June 22, 2023",
  },
  {
    name: "News App",
    imageUrl: "/images/news-app.webp",
    imageLight: "/images/news-app-l.webp",
    iconUrl: "/images/news-app.ico",
    linkName: "apps/news-app",
    date: "June 23, 2023",
  },
];
